/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_recompile_mobile_SdlMixerManager */

#ifndef _Included_org_recompile_mobile_SdlMixerManager
#define _Included_org_recompile_mobile_SdlMixerManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_recompile_mobile_SdlMixerManager
 * Method:    sdlMixerInit
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_org_recompile_mobile_SdlMixerManager_sdlMixerInit
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_recompile_mobile_SdlMixerManager
 * Method:    sdlMixerLoadMidi
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_recompile_mobile_SdlMixerManager_sdlMixerLoadMidi
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_recompile_mobile_SdlMixerManager
 * Method:    sdlMixerPlayMusic
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_recompile_mobile_SdlMixerManager_sdlMixerPlayMusic
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_recompile_mobile_SdlMixerManager
 * Method:    sdlMixerPauseMusic
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_recompile_mobile_SdlMixerManager_sdlMixerPauseMusic
  (JNIEnv *, jobject);

/*
 * Class:     org_recompile_mobile_SdlMixerManager
 * Method:    sdlMixerResumeMusic
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_recompile_mobile_SdlMixerManager_sdlMixerResumeMusic
  (JNIEnv *, jobject);

/*
 * Class:     org_recompile_mobile_SdlMixerManager
 * Method:    sdlMixerStopMusic
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_recompile_mobile_SdlMixerManager_sdlMixerStopMusic
  (JNIEnv *, jobject);

/*
 * Class:     org_recompile_mobile_SdlMixerManager
 * Method:    sdlMixerIsPlaying
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_recompile_mobile_SdlMixerManager_sdlMixerIsPlaying
  (JNIEnv *, jobject);

/*
 * Class:     org_recompile_mobile_SdlMixerManager
 * Method:    sdlMixerSetVolume
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_recompile_mobile_SdlMixerManager_sdlMixerSetVolume
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_recompile_mobile_SdlMixerManager
 * Method:    sdlMixerGetVolume
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_recompile_mobile_SdlMixerManager_sdlMixerGetVolume
  (JNIEnv *, jobject);

/*
 * Class:     org_recompile_mobile_SdlMixerManager
 * Method:    sdlMixerFreeMusic
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_recompile_mobile_SdlMixerManager_sdlMixerFreeMusic
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_recompile_mobile_SdlMixerManager
 * Method:    sdlMixerQuit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_recompile_mobile_SdlMixerManager_sdlMixerQuit
  (JNIEnv *, jclass);
  
JNIEXPORT jlong JNICALL Java_org_recompile_mobile_SdlMixerManager_sdlMixerLoadWav
  (JNIEnv *env, jobject obj, jstring filePath);
JNIEXPORT jint JNICALL Java_org_recompile_mobile_SdlMixerManager_sdlMixerPlayWav
  (JNIEnv *env, jobject obj, jlong musicHandle, jint loops);
JNIEXPORT void JNICALL Java_org_recompile_mobile_SdlMixerManager_sdlMixerPauseWav
  (JNIEnv *env, jobject obj);
JNIEXPORT void JNICALL Java_org_recompile_mobile_SdlMixerManager_sdlMixerResumeWav
  (JNIEnv *env, jobject obj);
JNIEXPORT void JNICALL Java_org_recompile_mobile_SdlMixerManager_sdlMixerStopWav
  (JNIEnv *env, jobject obj);
JNIEXPORT void JNICALL Java_org_recompile_mobile_SdlMixerManager_sdlMixerFreeWav
  (JNIEnv *env, jobject obj, jlong musicHandle);
JNIEXPORT jboolean JNICALL Java_org_recompile_mobile_SdlMixerManager_sdlMixerIsPlayingWav
  (JNIEnv *env, jobject obj);

JNIEXPORT void JNICALL Java_org_recompile_mobile_SdlMixerManager_sdlMixerSetVolumeWav
  (JNIEnv *env, jobject obj, jint volume);
  
JNIEXPORT jint JNICALL  JNI_OnLoad(JavaVM* vm, void* reserved);
JNIEXPORT void JNICALL JNI_OnUnload(JavaVM* vm, void* reserved);

#ifdef __cplusplus
}
#endif
#endif
