/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_recompile_mobile_PlatformPlayer */

#ifndef _Included_org_recompile_mobile_PlatformPlayer
#define _Included_org_recompile_mobile_PlatformPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_recompile_mobile_PlatformPlayer
 * Method:    _start
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_recompile_mobile_PlatformPlayer__1start
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
