/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_recompile_mobile_Audio */

#ifndef _Included_org_recompile_mobile_Audio
#define _Included_org_recompile_mobile_Audio

/*
 * Class:     org_recompile_mobile_Audio
 * Method:    _start
 * Signature: ([B)V
 */
extern "C" {
JNIEXPORT void JNICALL Java_org_recompile_mobile_Audio__1start
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_recompile_mobile_Audio
 * Method:    _stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_recompile_mobile_Audio__1stop
  (JNIEnv *, jclass, jint type);
  
JNIEXPORT void JNICALL Java_org_recompile_mobile_Audio__1setVol
  (JNIEnv *, jclass, jint);
  
JNIEXPORT void JNICALL Java_org_recompile_mobile_Audio__1destroy
  (JNIEnv *, jclass);
  
}



#endif
